version: '3.9'
services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_db-data:/var/opt/postgres/data
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
volumes:
  postgres_db-data:
