spring:
  datasource:
    url: ${DATASOURCE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
