spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl.auto: update
